// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Lexer.flex

/**
 * ============================================================
 *  Lexer.flex  —  Analizador lexico
 * ============================================================
 *
 *  Proposito:
 *  ----------
 *  Lee el codigo fuente (archivo .txt) y lo divide tokens. 
 *  Cada token representa una palabra clave,
 *  un numero, un operador, un identificador, etc.
 *
 *  Archivos de salida:
 *  ------------------
 *  1. _tokens.txt   -> lista de todos los tokens encontrados,
 *                     con su numero de linea, columna y nombre.
 *  2. _symbols.txt  -> tablas de simbolos organizadas por scope
 *                     (scope): cada funcion o bloque tiene su
 *                     propia tabla con las variables declaradas.
 *
 *  Restriccion: el lenguaje es case-sensitive ("If" ≠ "if").
 *  Recuperacion en modo panico ante errores lexicos.
 * ============================================================
 */

import java_cup.runtime.*;
import java.io.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\1\6\1\7\1\10\1\0\1\11\2\0"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\11\21"+
    "\1\22\1\0\1\23\1\0\1\24\1\0\1\25\4\26"+
    "\1\27\25\26\1\0\1\30\1\0\1\31\1\32\1\0"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\26\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\26\1\57\1\26"+
    "\1\60\1\26\1\61\1\62\1\63\1\64\42\0\1\65"+
    "\u015e\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\1\1\16\1\17\1\20\16\17\2\1\1\21\1\1"+
    "\1\0\1\22\2\0\1\23\1\24\3\0\1\25\1\26"+
    "\1\27\1\30\1\31\10\17\1\32\6\17\1\33\10\17"+
    "\1\0\1\34\1\35\1\2\2\36\1\37\1\0\1\40"+
    "\5\17\1\41\10\17\1\42\7\17\1\0\1\43\1\17"+
    "\1\44\1\17\1\45\1\46\1\47\1\17\1\50\12\17"+
    "\1\51\2\17\1\52\1\17\1\53\1\54\1\55\1\56"+
    "\6\17\1\57\3\17\1\60\1\17\1\61\1\62\1\63"+
    "\1\17\1\64\1\17\1\65\1\66\1\67\2\17\1\70"+
    "\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\66\0\154\0\66\0\242\0\66\0\66"+
    "\0\66\0\330\0\66\0\u010e\0\66\0\u0144\0\66\0\u017a"+
    "\0\u01b0\0\u01e6\0\u021c\0\66\0\u0252\0\66\0\u0288\0\u02be"+
    "\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e"+
    "\0\u04a4\0\u04da\0\u0510\0\u0546\0\u057c\0\u05b2\0\66\0\u05e8"+
    "\0\242\0\66\0\u061e\0\u0654\0\66\0\66\0\u068a\0\u06c0"+
    "\0\u06f6\0\66\0\66\0\66\0\66\0\66\0\u072c\0\u0762"+
    "\0\u0798\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6\0\u0252\0\u08dc"+
    "\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u0252\0\u0a20\0\u0a56"+
    "\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\66"+
    "\0\66\0\u0c06\0\66\0\u061e\0\u068a\0\u0c3c\0\u0c72\0\u0ca8"+
    "\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0252\0\u0db6\0\u0dec\0\u0e22"+
    "\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0252\0\u0f66\0\u0f9c"+
    "\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u0c3c\0\u1116"+
    "\0\u0252\0\u114c\0\u0252\0\u0252\0\u0252\0\u1182\0\u0252\0\u11b8"+
    "\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc\0\u1332\0\u1368"+
    "\0\u139e\0\u0252\0\u13d4\0\u140a\0\u0252\0\u1440\0\u0252\0\u0252"+
    "\0\u0252\0\u0252\0\u1476\0\u14ac\0\u14e2\0\u1518\0\u154e\0\u1584"+
    "\0\u0252\0\u15ba\0\u15f0\0\u1626\0\u165c\0\u1692\0\u0252\0\u0252"+
    "\0\u0252\0\u16c8\0\u0252\0\u16fe\0\u0252\0\u0252\0\u0252\0\u1734"+
    "\0\u176a\0\u17a0\0\u0252";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\2\1\17\2\20"+
    "\1\21\1\22\1\23\1\24\2\25\1\2\1\26\1\27"+
    "\1\25\1\30\1\31\1\32\1\33\1\34\1\35\1\25"+
    "\1\36\1\25\1\37\1\25\1\40\3\25\1\41\1\42"+
    "\1\43\1\25\1\44\1\25\1\45\1\46\1\2\1\47"+
    "\1\50\70\0\1\3\63\0\5\51\1\52\60\51\11\53"+
    "\1\0\16\53\1\54\35\53\13\0\1\55\67\0\1\56"+
    "\66\0\1\57\1\60\2\20\5\0\1\61\7\0\1\61"+
    "\110\0\1\62\20\0\1\63\5\0\1\64\36\0\1\65"+
    "\27\0\1\66\61\0\2\25\4\0\2\25\2\0\27\25"+
    "\25\0\2\25\4\0\2\25\2\0\1\67\26\25\25\0"+
    "\2\25\4\0\2\25\2\0\16\25\1\70\2\25\1\71"+
    "\5\25\25\0\2\25\4\0\2\25\2\0\1\25\1\72"+
    "\6\25\1\73\1\74\4\25\1\75\10\25\25\0\2\25"+
    "\4\0\2\25\2\0\5\25\1\76\10\25\1\77\10\25"+
    "\25\0\2\25\4\0\2\25\2\0\13\25\1\100\1\101"+
    "\3\25\1\102\6\25\25\0\2\25\4\0\2\25\2\0"+
    "\1\25\1\103\11\25\1\104\13\25\25\0\2\25\4\0"+
    "\2\25\2\0\21\25\1\105\5\25\25\0\2\25\4\0"+
    "\2\25\2\0\6\25\1\106\6\25\1\107\11\25\25\0"+
    "\2\25\4\0\2\25\2\0\5\25\1\110\21\25\25\0"+
    "\2\25\4\0\2\25\2\0\1\111\26\25\25\0\2\25"+
    "\4\0\2\25\2\0\5\25\1\112\21\25\25\0\2\25"+
    "\4\0\2\25\2\0\23\25\1\113\1\25\1\114\1\25"+
    "\25\0\2\25\4\0\2\25\2\0\21\25\1\115\5\25"+
    "\25\0\2\25\4\0\2\25\2\0\10\25\1\116\16\25"+
    "\22\0\1\117\72\0\1\120\1\0\1\121\126\0\1\122"+
    "\11\0\1\123\65\0\1\124\74\0\2\125\63\0\1\126"+
    "\67\0\1\127\64\0\2\25\4\0\2\25\2\0\14\25"+
    "\1\130\12\25\25\0\2\25\4\0\2\25\2\0\16\25"+
    "\1\131\10\25\25\0\2\25\4\0\2\25\2\0\5\25"+
    "\1\132\21\25\25\0\2\25\4\0\2\25\2\0\22\25"+
    "\1\133\4\25\25\0\2\25\4\0\2\25\2\0\1\25"+
    "\1\134\25\25\25\0\2\25\4\0\2\25\2\0\15\25"+
    "\1\135\11\25\25\0\2\25\4\0\2\25\2\0\24\25"+
    "\1\136\2\25\25\0\2\25\4\0\2\25\2\0\6\25"+
    "\1\137\20\25\25\0\2\25\4\0\2\25\2\0\22\25"+
    "\1\140\4\25\25\0\2\25\4\0\2\25\2\0\17\25"+
    "\1\141\7\25\25\0\2\25\4\0\2\25\2\0\24\25"+
    "\1\142\2\25\25\0\2\25\4\0\2\25\2\0\13\25"+
    "\1\143\13\25\25\0\2\25\4\0\2\25\2\0\16\25"+
    "\1\144\10\25\25\0\2\25\4\0\2\25\2\0\5\25"+
    "\1\145\21\25\25\0\2\25\4\0\2\25\2\0\23\25"+
    "\1\146\3\25\25\0\2\25\4\0\2\25\2\0\22\25"+
    "\1\147\4\25\25\0\2\25\4\0\2\25\2\0\5\25"+
    "\1\150\21\25\25\0\2\25\4\0\2\25\2\0\23\25"+
    "\1\151\3\25\25\0\2\25\4\0\2\25\2\0\21\25"+
    "\1\152\5\25\25\0\2\25\4\0\2\25\2\0\11\25"+
    "\1\153\15\25\25\0\2\25\4\0\2\25\2\0\24\25"+
    "\1\154\2\25\25\0\2\25\4\0\2\25\2\0\11\25"+
    "\1\155\15\25\5\0\15\117\1\156\50\117\2\122\1\3"+
    "\1\4\62\122\20\0\2\157\64\0\2\127\64\0\2\25"+
    "\4\0\2\25\2\0\1\25\1\160\25\25\25\0\2\25"+
    "\4\0\2\25\2\0\13\25\1\161\13\25\25\0\2\25"+
    "\4\0\2\25\2\0\1\25\1\162\25\25\25\0\2\25"+
    "\4\0\2\25\2\0\5\25\1\163\21\25\25\0\2\25"+
    "\4\0\2\25\2\0\21\25\1\164\5\25\25\0\2\25"+
    "\4\0\2\25\2\0\23\25\1\165\3\25\25\0\2\25"+
    "\4\0\2\25\2\0\1\25\1\166\25\25\25\0\2\25"+
    "\4\0\2\25\2\0\5\25\1\167\21\25\25\0\2\25"+
    "\4\0\2\25\2\0\23\25\1\170\3\25\25\0\2\25"+
    "\4\0\2\25\2\0\1\25\1\171\25\25\25\0\2\25"+
    "\4\0\2\25\2\0\22\25\1\172\4\25\25\0\2\25"+
    "\4\0\2\25\2\0\1\25\1\173\25\25\25\0\2\25"+
    "\4\0\2\25\2\0\1\25\1\174\25\25\25\0\2\25"+
    "\4\0\2\25\2\0\22\25\1\175\4\25\25\0\2\25"+
    "\4\0\2\25\2\0\20\25\1\176\6\25\25\0\2\25"+
    "\4\0\2\25\2\0\24\25\1\177\2\25\25\0\2\25"+
    "\4\0\2\25\2\0\11\25\1\200\15\25\25\0\2\25"+
    "\4\0\2\25\2\0\23\25\1\201\3\25\25\0\2\25"+
    "\4\0\2\25\2\0\5\25\1\202\21\25\25\0\2\25"+
    "\4\0\2\25\2\0\13\25\1\203\13\25\5\0\15\117"+
    "\1\156\45\117\1\3\2\117\20\0\2\25\4\0\2\25"+
    "\2\0\11\25\1\204\15\25\25\0\2\25\4\0\2\25"+
    "\2\0\12\25\1\205\14\25\25\0\2\25\4\0\2\25"+
    "\2\0\24\25\1\206\2\25\25\0\2\25\4\0\2\25"+
    "\2\0\26\25\1\207\25\0\2\25\4\0\2\25\2\0"+
    "\13\25\1\210\13\25\25\0\2\25\4\0\2\25\2\0"+
    "\5\25\1\211\21\25\25\0\2\25\4\0\2\25\2\0"+
    "\23\25\1\212\3\25\25\0\2\25\4\0\2\25\2\0"+
    "\23\25\1\213\3\25\25\0\2\25\4\0\2\25\2\0"+
    "\1\214\26\25\25\0\2\25\4\0\2\25\2\0\24\25"+
    "\1\215\2\25\25\0\2\25\4\0\2\25\2\0\21\25"+
    "\1\216\5\25\25\0\2\25\4\0\2\25\2\0\15\25"+
    "\1\217\11\25\25\0\2\25\4\0\2\25\2\0\3\25"+
    "\1\220\23\25\25\0\2\25\4\0\2\25\2\0\5\25"+
    "\1\221\21\25\25\0\2\25\4\0\2\25\2\0\15\25"+
    "\1\222\11\25\25\0\2\25\4\0\2\25\2\0\13\25"+
    "\1\223\13\25\25\0\2\25\4\0\2\25\2\0\10\25"+
    "\1\224\16\25\25\0\2\25\4\0\2\25\2\0\23\25"+
    "\1\225\3\25\25\0\2\25\4\0\2\25\2\0\1\25"+
    "\1\226\25\25\25\0\2\25\4\0\2\25\2\0\15\25"+
    "\1\227\11\25\25\0\2\25\4\0\2\25\2\0\7\25"+
    "\1\230\17\25\25\0\2\25\4\0\2\25\2\0\10\25"+
    "\1\231\16\25\25\0\2\25\4\0\2\25\2\0\1\232"+
    "\26\25\25\0\2\25\4\0\2\25\2\0\23\25\1\233"+
    "\3\25\25\0\2\25\4\0\2\25\2\0\5\25\1\234"+
    "\21\25\25\0\2\25\4\0\2\25\2\0\5\25\1\235"+
    "\21\25\25\0\2\25\4\0\2\25\2\0\13\25\1\236"+
    "\13\25\25\0\2\25\4\0\2\25\2\0\1\237\26\25"+
    "\25\0\2\25\4\0\2\25\2\0\21\25\1\240\5\25"+
    "\25\0\2\25\4\0\2\25\2\0\1\241\26\25\25\0"+
    "\2\25\4\0\2\25\2\0\23\25\1\242\3\25\25\0"+
    "\2\25\4\0\2\25\2\0\5\25\1\243\21\25\5\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6102];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\1\1\3\11\1\1\1\11"+
    "\1\1\1\11\1\1\1\11\4\1\1\11\1\1\1\11"+
    "\20\1\1\11\1\1\1\0\1\11\2\0\2\11\3\0"+
    "\5\11\30\1\1\0\2\11\1\1\1\11\2\1\1\0"+
    "\27\1\1\0\65\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // ==============================================================
    //  ESCRITURA DE TOKENS
    // ==============================================================

    // escribe el archivo _tokens.txt
    private static PrintWriter tokenWriter = null;

    // guarda un numero unico por cada lexema distinto.
    private static java.util.LinkedHashMap<String, Integer> lexemaIds =
        new java.util.LinkedHashMap<>();
    private static int nextLexemaId = 1;

    // Abre el archivo _tokens.txt y escribe la cabecera de la tabla.
    public static void initTokenWriter(String filename) throws IOException {
        tokenWriter = new PrintWriter(new FileWriter(filename));
        tokenWriter.println("ID_LEXEMA \tLiNEA \tCOLUMNA \tTOKEN                \tLEXEMA");
        tokenWriter.println("-------------------------------------------------------------------------------");
    }

    // Cierra el archivo de tokens.
    public static void closeTokenWriter() {
        if (tokenWriter != null) {
            tokenWriter.close();
            tokenWriter = null;
        }
    }

    // Devuelve el ID de un lexema; si no existe, le asigna uno nuevo.
    private int getLexemaId(String lexema) {
        if (!lexemaIds.containsKey(lexema)) {
            lexemaIds.put(lexema, nextLexemaId++);
        }
        return lexemaIds.get(lexema);
    }

    // Crea un token sin valor adicional (para operadores y palabras reservadas).
    private Symbol symbol(int type) {
        String tokenName = sym.terminalNames[type];
        String lexema = yytext();
        int lexId = getLexemaId(lexema);
        writeToken(lexId, tokenName, lexema);
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }

    // Crea un token con valor (para literales numericos, strings, etc.).
    private Symbol symbol(int type, Object value) {
        String tokenName = sym.terminalNames[type];
        String lexema = yytext();
        int lexId = getLexemaId(lexema);
        writeToken(lexId, tokenName, lexema);
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }

    // Escribe una linea en el archivo _tokens.txt.
    private void writeToken(int lexId, String tokenName, String lexema) {
        if (tokenWriter != null) {
            tokenWriter.printf("%-10d\t%-6d\t%-8d\t%-21s\t%s%n",
                lexId, yyline + 1, yycolumn + 1, tokenName, lexema);
            tokenWriter.flush();
        }
    }

    // ==============================================================
    //  TABLAS DE SiMBOLOS POR SCOPE
    // ==============================================================

    // lista de mapas (nombre de variable -> informacion).
    private static java.util.ArrayList<java.util.LinkedHashMap<String, String[]>> symbolTables =
        new java.util.ArrayList<>();

    // nombres de los ambitos en el mismo orden.
    private static java.util.ArrayList<String> tableNames = new java.util.ArrayList<>();
    private static PrintWriter symbolWriter = null;

    // Abre el archivo _symbols.txt.
    public static void initSymbolWriter(String filename) throws IOException {
        symbolWriter = new PrintWriter(new FileWriter(filename));
    }

    // Cierra el archivo _symbols.txt escribiendo todas las tablas de simbolos.
    public static void closeSymbolWriter() {
        if (symbolWriter != null) {
            symbolWriter.println("================================================================================");
            symbolWriter.println("TABLAS DE SiMBOLOS POR SCOPE");
            symbolWriter.println("================================================================================");
            for (int i = 0; i < symbolTables.size(); i++) {
                String tableName = tableNames.get(i);
                java.util.LinkedHashMap<String, String[]> table = symbolTables.get(i);
                symbolWriter.println();
                symbolWriter.println("SCOPE: " + tableName);
                symbolWriter.println("-------------------------------------------------------------------------------");
                symbolWriter.println("NOMBRE            \tTIPO              \tPARAMETRO             \tLiNEA \tCOLUMNA");
                symbolWriter.println("-------------------------------------------------------------------------------");
                for (java.util.Map.Entry<String, String[]> entry : table.entrySet()) {
                    String[] info = entry.getValue();
                    symbolWriter.printf("%-18s\t%-18s\t%-18s\t%-6s\t%s%n",
                        entry.getKey(), info[0], info[1], info[2], info[3]);
                }
            }
            symbolWriter.close();
            symbolWriter = null;
        }
    }

    // ==============================================================
    //  PILA DE SCOPES
    // ==============================================================

    // La pila permite saber en que scope se esta en cada momento.
    // Cada scope tiene un nombre compuesto por la concatenacion
    // de todos los niveles, separados por "_" (ej: "main_do1_switch2_case3").
    private static java.util.Stack<String> scopeStack = new java.util.Stack<>();
    public static int ifCount    = 0;
    public static int doCount    = 0;
    public static int switchCount= 0;
    public static int caseCount  = 0;
    public static int elseCount  = 0;

    // Apila un nuevo scope. Si no existe tabla para el, la crea.
    public static void pushScope(String scopeName) {
        scopeStack.push(scopeName);
        String fullName = String.join("_", scopeStack);
        if (!tableNames.contains(fullName)) {
            tableNames.add(fullName);
            symbolTables.add(new java.util.LinkedHashMap<String, String[]>());
        }
    }

    // Desapila el scope actual.
    public static void popScope() {
        if (!scopeStack.isEmpty()) scopeStack.pop();
    }

    // Apila un scope de tipo "if".
    public static void pushIfScope(String funcName) {
        ifCount++;
        pushScope("if" + ifCount);
    }

    // Apila un scope de tipo "else".
    public static void pushElseScope(String funcName) {
        elseCount++;
        pushScope("else" + elseCount);
    }

    // Apila un scope de tipo "do" (do-while).
    public static void pushDoScope(String funcName) {
        doCount++;
        pushScope("do" + doCount);
    }

    // Apila un scope de tipo "switch". Reinicia el contador de cases.
    public static void pushSwitchScope(String funcName) {
        caseCount = 0;
        switchCount++;
        pushScope("switch" + switchCount);
    }

    // Apila un scope de tipo "case" o "default".
    public static void pushCaseScope(String funcName, String cName) {
        caseCount++;
        pushScope(cName + caseCount);
    }

    // Agrega un simbolo (variable o parametro) a la tabla del scope actual.
    public static void addSymbol(String name, String tipo, String parametro, int line, int col) {
        if (scopeStack.isEmpty()) return;
        String fullName = String.join("_", scopeStack);
        int tableIndex  = tableNames.indexOf(fullName);
        if (tableIndex >= 0) {
            java.util.LinkedHashMap<String, String[]> table = symbolTables.get(tableIndex);
            if (!table.containsKey(name)) {
                table.put(name, new String[]{ tipo, parametro,
                    String.valueOf(line), String.valueOf(col) });
            }
        }
    }

    // Reinicia todos los contadores de estructuras de control.
    // Se llama al entrar a cada funcion nueva.
    public static void resetControlCounters() {
        ifCount     = 0;
        elseCount   = 0;
        doCount     = 0;
        switchCount = 0;
        caseCount   = 0;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { String lex = yytext();
                            int lin = yyline + 1, col = yycolumn + 1;
                            System.err.println("Error lexico en linea " + lin +
                                ", columna " + col +
                                ": caracter no reconocido '" + lex + "'");
                            return new Symbol(sym.error, lin, col, lex);
            }
          // fall through
          case 58: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 59: break;
          case 3:
            { return symbol(sym.EXCLAMATION);
            }
          // fall through
          case 60: break;
          case 4:
            { return symbol(sym.OR);
            }
          // fall through
          case 61: break;
          case 5:
            { return symbol(sym.NOT);
            }
          // fall through
          case 62: break;
          case 6:
            { return symbol(sym.MOD);
            }
          // fall through
          case 63: break;
          case 7:
            { return symbol(sym.TIMES);
            }
          // fall through
          case 64: break;
          case 8:
            { return symbol(sym.PLUS);
            }
          // fall through
          case 65: break;
          case 9:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 66: break;
          case 10:
            { return symbol(sym.MINUS);
            }
          // fall through
          case 67: break;
          case 11:
            { return symbol(sym.DIVIDE);
            }
          // fall through
          case 68: break;
          case 12:
            { return symbol(sym.INT_LIT, Integer.parseInt(yytext()));
            }
          // fall through
          case 69: break;
          case 13:
            { return symbol(sym.COLON);
            }
          // fall through
          case 70: break;
          case 14:
            { return symbol(sym.AND);
            }
          // fall through
          case 71: break;
          case 15:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 72: break;
          case 16:
            { return symbol(sym.POWER);
            }
          // fall through
          case 73: break;
          case 17:
            { return symbol(sym.SEPARATOR);
            }
          // fall through
          case 74: break;
          case 18:
            { String str = yytext();
                            return symbol(sym.STRING_LIT, str.substring(1, str.length() - 1));
            }
          // fall through
          case 75: break;
          case 19:
            { return symbol(sym.INCREMENT);
            }
          // fall through
          case 76: break;
          case 20:
            { return symbol(sym.DECREMENT);
            }
          // fall through
          case 77: break;
          case 21:
            { return symbol(sym.RBLOCK);
            }
          // fall through
          case 78: break;
          case 22:
            { return symbol(sym.ASSIGN);
            }
          // fall through
          case 79: break;
          case 23:
            { return symbol(sym.LBRACKET);
            }
          // fall through
          case 80: break;
          case 24:
            { return symbol(sym.LPAR);
            }
          // fall through
          case 81: break;
          case 25:
            { return symbol(sym.RBRACKET);
            }
          // fall through
          case 82: break;
          case 26:
            { return symbol(sym.DO);
            }
          // fall through
          case 83: break;
          case 27:
            { return symbol(sym.IF);
            }
          // fall through
          case 84: break;
          case 28:
            { return symbol(sym.LBLOCK);
            }
          // fall through
          case 85: break;
          case 29:
            { return symbol(sym.RPAR);
            }
          // fall through
          case 86: break;
          case 30:
            { return symbol(sym.CHAR_LIT, yytext().charAt(1));
            }
          // fall through
          case 87: break;
          case 31:
            { return symbol(sym.FLOAT_LIT, Float.parseFloat(yytext()));
            }
          // fall through
          case 88: break;
          case 32:
            { return symbol(sym.EXP_LIT, yytext());
            }
          // fall through
          case 89: break;
          case 33:
            { return symbol(sym.CIN);
            }
          // fall through
          case 90: break;
          case 34:
            { return symbol(sym.INT);
            }
          // fall through
          case 91: break;
          case 35:
            { return symbol(sym.FRAC_LIT, yytext());
            }
          // fall through
          case 92: break;
          case 36:
            { return symbol(sym.BOOL);
            }
          // fall through
          case 93: break;
          case 37:
            { return symbol(sym.CASE);
            }
          // fall through
          case 94: break;
          case 38:
            { return symbol(sym.CHAR);
            }
          // fall through
          case 95: break;
          case 39:
            { return symbol(sym.COUT);
            }
          // fall through
          case 96: break;
          case 40:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 97: break;
          case 41:
            { return symbol(sym.BOOL_LIT, Boolean.valueOf(true));
            }
          // fall through
          case 98: break;
          case 42:
            { return symbol(sym.BREAK);
            }
          // fall through
          case 99: break;
          case 43:
            { return symbol(sym.EMPTY);
            }
          // fall through
          case 100: break;
          case 44:
            { return symbol(sym.EQUAL);
            }
          // fall through
          case 101: break;
          case 45:
            { return symbol(sym.BOOL_LIT, Boolean.valueOf(false));
            }
          // fall through
          case 102: break;
          case 46:
            { return symbol(sym.FLOAT);
            }
          // fall through
          case 103: break;
          case 47:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 104: break;
          case 48:
            { return symbol(sym.LESS_T);
            }
          // fall through
          case 105: break;
          case 49:
            { return symbol(sym.RETURN);
            }
          // fall through
          case 106: break;
          case 50:
            { return symbol(sym.STRING);
            }
          // fall through
          case 107: break;
          case 51:
            { return symbol(sym.SWITCH);
            }
          // fall through
          case 108: break;
          case 52:
            { return symbol(sym.DEFAULT);
            }
          // fall through
          case 109: break;
          case 53:
            { return symbol(sym.LESS_TE);
            }
          // fall through
          case 110: break;
          case 54:
            { return symbol(sym.N_EQUAL);
            }
          // fall through
          case 111: break;
          case 55:
            { return symbol(sym.MAIN);
            }
          // fall through
          case 112: break;
          case 56:
            { return symbol(sym.GREATHER_T);
            }
          // fall through
          case 113: break;
          case 57:
            { return symbol(sym.GREATHER_TE);
            }
          // fall through
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
